name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Link code into GOPATH
        run: |
          mkdir -p $(go env GOPATH)/src/github.com/charypar
          rm -rf $(go env GOPATH)/src/github.com/charypar/monobuild
          ln -s $(pwd) $(go env GOPATH)/src/github.com/charypar/monobuild

      - name: Build
        run: |
          make

      - name: Test
        run: |
          make test
